# Generated by Django 5.1.7 on 2025-05-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("""
                    CREATE TABLE todo_post (
                        id serial primary key,
                        title varchar(255) NOT NULL,
                        content text NOT NULL,
                        created_at date default now()
                    );
                """)
            ], 

            reverse_sql=[
                ("""
                    drop table if exists todo_post;
                """)
            ])
    ]
